import { NextResponse } from "next/server";

// Get six images from StabilityAI using the image prompts generated by getPrompts(storyText)
export async function POST(req) {
  const body = await req.json();
  const { story } = body;

   // Verify that theme is correctly received
   //console.log("Received theme in API route:", theme);

  let allImages = [];
  const prompts = await getPrompts(story);
 
  console.log("prompts-route", prompts);

  for (let i = 0; i < prompts.length; i++) {
    const text_prompts = [{ text: prompts[i] }];
 
    const response = await fetch(
      "https://api.stability.ai/v1/generation/stable-diffusion-v1-6/text-to-image",
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${process.env.STABILITY_API_KEY}`,
        },
        body: JSON.stringify({ text_prompts }),
      }
    );
    const images = await response.json();

    allImages.push(images.artifacts[0].base64);

  }
  return NextResponse.json({ images: allImages });
}
//|a boy playing with a cute friendly pet dinosaur, ${style}
//a castle high on mountain touching the clouds, ${style}|a boy playing on a bright sunny day at the park, ${style}|
//|a red canoe drifting on a peacefull lake, ${style}

// Get six image prompts from OpenAI using the story generated by fetchStory(inputPrompt)
async function getPrompts(story) {
  const OpenAI = require("openai");

  //console.log("themeGP", theme)

  const themeStyle = 
    "Art by Maurice Brazil Prendergast, Charline von Heyl, Michael Leunig, Edward Okun, Anna Dittmann, Kazumasa Nagai, Desmond Morris. Intricate, beautiful, cute. Watercolor and ink, volumetric lighting."
 // Avoid including words like "mystical", "shimmering", and "glimmering" in prompts.
  // console.log("styleGP", styles)

  // if (theme === "Weird") {
  //   themeStyle = styles[0]
  // }
  // if (theme === "Spooky") {
  //   themeStyle = styles[1]
  // }
  // if (theme === "Cute") {
  //   themeStyle = styles[2]
  // }
  // else {
  //   themeStyle = styles[3]
  // }

  //console.log("themeStyleGp", themeStyle)


  const openai = new OpenAI(process.env.OPENAI_API_KEY);
  const response = await openai.chat.completions.create({
    model: "gpt-3.5-turbo-16k",
    messages: [
      {
        role: "system",
        content: `Your job is to generate two image prompts for the following story.
                  Use ${themeStyle} for all two prompts.
                  Each prompt should be a descriptive sentence.      
                  Please list the two prompts, separated by a "|" symbol.
                  For example:"a black cat near a dark spooky old house at night, ${themeStyle}|a beautifull woman crossing a bustling city street, ${themeStyle}".`,
      },
      {
        role: "user",
        content: `story: ${story}\n`,
      },
    ],
  });
  const prompts =
    response.choices[0]?.message?.content?.trim().split("|") || "";
    console.log("story-prompts", prompts);
  return prompts;
}